version: "2"

services:

  mysql:
    image: c5-mysql
    container_name: c5-mysql
    build: ./docker/mysql
    ports:
    - "3333:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - ./db_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf

  app:
    image: c5-app
    container_name: c5-app
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    volumes:
      - ./src/concrete5-master:/var/www/html/
    links:
      - mysql

  nginx:
    image: c5-nginx
    container_name: c5-nginx
    build: ./docker/nginx
    volumes:
      - ./src/concrete5-master:/var/www/html/
    ports:
      - "80:80"
      - "443:443"
    links:
      - app
